/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMultiSigMetadata,
  IMultiSigMetadataInterface,
} from "../../extensions/IMultiSigMetadata";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMultiSigMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IMultiSigMetadataInterface {
    return new Interface(_abi) as IMultiSigMetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMultiSigMetadata {
    return new Contract(address, _abi, runner) as unknown as IMultiSigMetadata;
  }
}
