/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMultiSigMetadata__factory } from "./IMultiSigMetadata__factory";
export { MultiSigMetadata__factory } from "./MultiSigMetadata__factory";
