/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMultiSigMetadata } from "./IMultiSigMetadata";
export type { MultiSigMetadata } from "./MultiSigMetadata";
